### ISSUE TITLE
Boot Error Clover n5110 

### ISSUE THREAD

**Issue by CreativeArtDesign** [CloverHackyColor/CloverBootloader#124]
I getting boot error see picture log
I using Cataling 10.15.4 and the newest update for Catalina.
I have 5108 right now working.

- Hardware: MSI AMD Radion IV
- Motherboard Gigabyte Z390 Designare
- Memory 32 GB 16x2
- 5 SSD(500GB each) AND - 1 M2 1TB Drives Samsung 970 Pro (Master boot)
- Bluetooth Asus UBS Stick
- Apple Keyboard Grey pro

Updated to r5110 but no success on boot. The same problem as r5109 halted after the choice of drives. See log.
![boot 5110](https://user-images.githubusercontent.com/46310335/79043045-4e62cd00-7c05-11ea-81d0-dab7d4e3bb15.jpg)

**Comment by mKlus** [comment]
@CreativeArtDesign I've been experiencing issues since I installed Clover 5108 too and have the same or similar error. I went back to 5107 but still have the issue occasionally.
What fixes it for me is booting into recovery and run 
kextcache -i /Volumes/Catalina
Where Catalina is the name of the disk where Catalina is installed.

**Comment by SergeySlice** [comment]
Test 5111
