### ISSUE TITLE
Can't update Catalina to BigSur with 5124

### ISSUE THREAD

**Issue by abace18** [CloverHackyColor/CloverBootloader#262]
![IMG_20201012_220333](https://user-images.githubusercontent.com/62308926/95823962-2df00880-0d37-11eb-888e-376b8c878671.jpg)

**Comment by sn0wfL4ke98** [comment]
just about VoodooInput.kext. Remove it from kexts/Other folder, also from PlugIns folder in VoodooPS2Controller.kext

**Comment by abace18** [comment]
> just about VoodooInput.kext. Remove it from kexts/Other folder, also from PlugIns folder in VoodooPS2Controller.kext


![IMG_0289](https://user-images.githubusercontent.com/62308926/95883397-8cdb6f00-0d83-11eb-8519-dd616cab36c9.jpg)

**Comment by zty199** [comment]
Try to add boot-args "npci=0x2000", this may get you some help......

**Comment by sn0wfL4ke98** [comment]
what is your laptop spec?

**Comment by abace18** [comment]
> what is your laptop spec?

![Screen Shot 2020-10-14 at 08 02 48](https://user-images.githubusercontent.com/62308926/95945682-b338f300-0df3-11eb-87f5-e87268e2dbcd.png)

**Comment by sn0wfL4ke98** [comment]
- use some common kexts like VirtualSMC, Lilu, WEG, AppleALC, VoodooPS2Controller, VoodooI2C, VoodooI2CHID, NoTouchID, SMCProcessor, SMCBatteryManager. Currently forget about AsusSMC. Also remember to remove the VoodooInput.kext like i said
- about ACPI, because that CPU is gen 8th Coffeelake, so you should need EC-USBX, PLUG, PNLF (coffeelake version) and XOSI. You can grab the prebuilt of them from Dortania OpenCore. Then try to make the config.plist again and carefully.
- about ACPI patches, only rename _OSI to XOSI is fine. Because make sure that can boot with USB
- that CPU is gen 8 but Whiskey Lake, mean the iGPU is UHD620 iirc. You have to fake the id with device-id = 9B3E0000

**Comment by abace18** [comment]
> * use some common kexts like VirtualSMC, Lilu, WEG, AppleALC, VoodooPS2Controller, VoodooI2C, VoodooI2CHID, NoTouchID, SMCProcessor, SMCBatteryManager. Currently forget about AsusSMC. Also remember to remove the VoodooInput.kext like i said
> * about ACPI, because that CPU is gen 8th Coffeelake, so you should need EC-USBX, PLUG, PNLF (coffeelake version) and XOSI. You can grab the prebuilt of them from Dortania OpenCore. Then try to make the config.plist again and carefully.
> * about ACPI patches, only rename _OSI to XOSI is fine. Because make sure that can boot with USB
> * that CPU is gen 8 but Whiskey Lake, mean the iGPU is UHD620 iirc. You have to fake the id with device-id = 9B3E0000

Tried everything you said, but directly with OpenCore, and I also got a kernel panic.

**Comment by SergeySlice** [comment]
The hang at system start process means an error or incompatibility of one you kext with BigSur. 
Clover has nothing to do with this.
