### ISSUE TITLE
The USB mouse cannot work if boot7.

### ISSUE THREAD

**Issue by 1457384613gh** [CloverHackyColor/CloverBootloader#601]
The USB mouse cannot work if `boot7`.<br/>
What I use is DuetPkg of Clover.<br/>
`MBR`=>`PBR`=>`boot` (`boot7` renamed)=>`CLOVERX64.efi`<br/>
The USB mouse cannot work.<br/>
The USB mouse can work if `boot6`.

**Comment by SergeySlice** [comment]
Look for driver UsbMouseDxe.efi.
May be it helps you.

**Comment by SergeySlice** [comment]
boot7 was created with option --no-usb. But yes, it should use driver of LegacyBIOS. 
If BIOS has option "emulate PS2" or something similar.

**Comment by SergeySlice** [comment]
First of all, your observation is unique for you, not common.
There can't be universal solution for all mice, keyboards or touchpad. We made more or less universal drivers supporting wide range of devices but not all.
You probably know that touchpad can be Alps, Synaptic, Sentelic and others and they have different drivers?
boot7 works with devices which is supported by BIOS due to boot7 calls to INT10, 15 etc.
boot6 has own set of drivers based on EDKII sources.
We can't do something more.
