### ISSUE TITLE
changing configuration on the fly via GUI is not getting saved

### ISSUE THREAD

**Issue by ryanrudolfoba** [CloverHackyColor/CloverBootloader#615]
I'm using the default clover config.plist located in efi/clover/config.plist

Clover boots up when I start my computer and the Clover GUI shows up, I try to edit the configurations on the fly via the GUI but it doesnt save on the next reboot the changes I did is lost.

Is there a way to set options on the fly using the GUI and have it saved? I've tried it on both 5151 and 5152 same behavior. Thanks!

**Comment by SergeySlice** [comment]
There was an utility "clover-genconfig" which can remember last used settings after boot into system. But partially because it is very complex to restore settings as plist while you changed variables calculated from the config.
So you should remember your settings and after successful boot write them into config.plist
