### ISSUE TITLE
R5105 Unable to boot linux (kubuntu)

### ISSUE THREAD

**Issue by pagimamaun** [CloverHackyColor/CloverBootloader#96]
Hello
I use clover for multi-boot: Catalina, Windows 10, kubuntu 19,10
After this update, i was unable to start kubuntu with clover
Grub starting fine but after starting kubuntu i'm stuck on black screen
With verbose loading is stuck on "loading ramdisk"
Thanks for your help

**Comment by SergeySlice** [comment]
Any information? How to reproduce?

**Comment by asava** [comment]
I can confirm how this issue can be produced, but it is not caused by Clover.
You are using OcQuirks, right?
This is caused by OpenRuntime.efi (or FwRuntimeServices.efi in older versions).

Steps to reproduce:
1. boot to shell (without Clover at all)
2. load OpenRuntime.efi (or FwRuntimeServices.efi in older versions).
3. start grubx64.efi
The same behavior you are describing will occur.

If this is the case, please report this to the OpenCore team.

**Comment by pagimamaun** [comment]
Hello
Thank you for your response
The problem was reported to open core team
A new version of ocquirks was done and now all is ok with kubuntu boot
Thanks for your help
